### ISSUE TITLE
Observing carbon log error when starting ballerina image

### ISSUE THREAD

**Issue by gvasanka** [ballerinalang/container-support#16]
Steps:
1. Build base ballerina base image
2. Create new image with ballerina service included with below command
./ballerina docker /home/asankav/svn/ballerina_test/services/artifacts/wokerSupport/workerservice.bsz -t dockimage 
ballerina: build docker image [dockimage:latest] in docker host [localhost]? (y/n): y

3. started docker image with the following command
 docker run dockimage:latest

Issue:
Observing following

asankav@asankav-ThinkPad-T540p:~/servers/bal/ballerina-0.8.0-SNAPSHOT/bin$ docker run dockimage:latest
Running: ballerina run service /ballerina/files/workerservice.bsz
ballerina: deploying service(s) in '/ballerina/files/workerservice.bsz'
Can't load log handler "java.util.logging.FileHandler"
java.nio.file.NoSuchFileException: logs/carbon.log.lck
java.nio.file.NoSuchFileException: logs/carbon.log.lck
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
	at sun.nio.fs.UnixFileSystemProvider.newFileChannel(UnixFileSystemProvider.java:177)
	at java.nio.channels.FileChannel.open(FileChannel.java:287)
	at java.nio.channels.FileChannel.open(FileChannel.java:335)
	at java.util.logging.FileHandler.openFiles(FileHandler.java:459)
	at java.util.logging.FileHandler.<init>(FileHandler.java:263)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at java.util.logging.LogManager$5.run(LogManager.java:966)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.util.logging.LogManager.loadLoggerHandlers(LogManager.java:958)
	at java.util.logging.LogManager.initializeGlobalHandlers(LogManager.java:1578)
	at java.util.logging.LogManager.access$1500(LogManager.java:145)
	at java.util.logging.LogManager$RootLogger.accessCheckedHandlers(LogManager.java:1667)
	at java.util.logging.Logger.getHandlers(Logger.java:1777)
	at java.util.logging.Logger.log(Logger.java:735)
	at io.netty.util.internal.logging.JdkLogger.log(JdkLogger.java:606)
	at io.netty.util.internal.logging.JdkLogger.warn(JdkLogger.java:420)
	at io.netty.util.internal.MacAddressUtil.defaultMachineId(MacAddressUtil.java:139)
	at io.netty.channel.DefaultChannelId.<clinit>(DefaultChannelId.java:100)
	at io.netty.channel.AbstractChannel.newId(AbstractChannel.java:107)
	at io.netty.channel.AbstractChannel.<init>(AbstractChannel.java:79)
	at io.netty.channel.nio.AbstractNioChannel.<init>(AbstractNioChannel.java:84)
	at io.netty.channel.nio.AbstractNioMessageChannel.<init>(AbstractNioMessageChannel.java:42)
	at io.netty.channel.socket.nio.NioServerSocketChannel.<init>(NioServerSocketChannel.java:85)
	at io.netty.channel.socket.nio.NioServerSocketChannel.<init>(NioServerSocketChannel.java:71)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at io.netty.channel.ReflectiveChannelFactory.newChannel(ReflectiveChannelFactory.java:38)
	at io.netty.bootstrap.AbstractBootstrap.initAndRegister(AbstractBootstrap.java:319)
	at io.netty.bootstrap.AbstractBootstrap.doBind(AbstractBootstrap.java:281)
	at io.netty.bootstrap.AbstractBootstrap.bind(AbstractBootstrap.java:277)
	at org.wso2.carbon.transport.http.netty.listener.ServerConnectorController.bindInterface(ServerConnectorController.java:185)
	at org.wso2.carbon.transport.http.netty.listener.HTTPServerConnector.start(HTTPServerConnector.java:54)
	at org.ballerinalang.natives.connectors.BallerinaConnectorManager.startPendingConnectors(BallerinaConnectorManager.java:173)
	at org.ballerinalang.launcher.BProgramRunner.runServices(BProgramRunner.java:67)
	at org.ballerinalang.launcher.Main$RunServiceCmd.execute(Main.java:455)
	at org.ballerinalang.launcher.Main$RunCmd.execute(Main.java:294)
	at java.util.Optional.ifPresent(Optional.java:159)
	at org.ballerinalang.launcher.Main.main(Main.java:48)
[2017-02-18 10:13:31,725] WARNING {io.netty.util.internal.MacAddressUtil defaultMachineId} - Failed to find a usable hardware address from the network interfaces; using random bytes: 8b:9b:0d:af:55:e9:06:29 
ballerina: started server connector http-9090

**Comment by chamilad** [comment]
This stack trace was removed by creating the `logs` directory if it doesn't exist. This has been fixed by commit 8449b975544250b6f2460ed8295846ab233e89e8.
